/**
 * Autogenerated by renren-api2-generator 2014-04-23 18:03:22
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
/**
 * 访问控制
 */
 public enum AccessControl {
	/*
	 * 仅自己可见
	 */
	PRIVATE,	
	/*
	 * 所有人可见
	 */
	PUBLIC,	
	/*
	 * 密码访问可见
	 */
	PASSWORD,	
	/*
	 * 仅好友可见
	 */
	FRIEND;	
}
