/**
 * Autogenerated by renren-api2-generator 2013-11-21 17:47:04
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
import java.util.*;
/**
 *
 * 用户账号信息。
 */
public class Account {
	
	/**
	 * 用户账号
	 */
	private String account;
	/**
	 * 用户ID
	 */
	private long userId;
	public void setAccount(String account) {
		this.account = account;
	}
	public String getAccount() {
		return this.account;
	}
	public void setUserId(long userId) {
		this.userId = userId;
	}
	public long getUserId() {
		return this.userId;
	}
}
