/**
 * Autogenerated by renren-api2-generator 2013-11-21 17:47:04
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
import java.util.*;
/**
 *
 * 活动信息
 */
public class ActivityResponse {
	
	/**
	 * 活动类型
	 */
	private int activityType;
	/**
	 * 徽章地址
	 */
	private String badgeUrl;
	public void setActivityType(int activityType) {
		this.activityType = activityType;
	}
	public int getActivityType() {
		return this.activityType;
	}
	public void setBadgeUrl(String badgeUrl) {
		this.badgeUrl = badgeUrl;
	}
	public String getBadgeUrl() {
		return this.badgeUrl;
	}
}
