/**
 * Autogenerated by renren-api2-generator 2013-03-13 15:27:21
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
/**
 * 相册的类型。
 */
 public enum AlbumType {
	/*
	 * 头像相册
	 */
	PORTRAIT,	
	/*
	 * APP相册
	 */
	APP,	
	/*
	 * 普通相册
	 */
	GENERAL,	
	/*
	 * 快速上传相册
	 */
	PUBLISHER_SINGLE,	
	/*
	 * 其他相册
	 */
	OTHER,	
	/*
	 * 日志相册
	 */
	BLOG,	
	/*
	 * 应用相册
	 */
	ALL_APP,	
	/*
	 * 语音相册
	 */
	VOICE,	
	/*
	 * 大头贴相册
	 */
	HEADPHOTO,	
	/*
	 * 活动相册
	 */
	ACTIVE,	
	/*
	 * 手机相册
	 */
	MMS;	
}
