/**
 * Autogenerated by renren-api2-generator 2014-04-23 18:03:22
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
import java.util.*;
/**
 *
 * App
 */
public class App {
	
	/**
	 * 应用ID
	 */
	private long id;
	/**
	 * 应用名称
	 */
	private String name;
	/**
	 * 应用图标列表
	 */
	private List<Icon> icons;
	/**
	 * 应用描述
	 */
	private String description;
	/**
	 * 应用公共主页id
	 */
	private long pageId;
	public void setId(long id) {
		this.id = id;
	}
	public long getId() {
		return this.id;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getName() {
		return this.name;
	}
	public void setIcons(List<Icon> icons) {
		this.icons = icons;
	}
	public List<Icon> getIcons() {
		return this.icons;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public String getDescription() {
		return this.description;
	}
	public void setPageId(long pageId) {
		this.pageId = pageId;
	}
	public long getPageId() {
		return this.pageId;
	}
}
