/**
 * Autogenerated by renren-api2-generator 2013-03-23 13:10:03
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
/**
 * 
 */
 public enum BlogType {
	/*
	 * 通过API发表的日志
	 */
	TYPE_API,	
	/*
	 * rss导入的日志
	 */
	TYPE_RSS,	
	/*
	 * web发表的日志
	 */
	TYPE_DEFAULT,	
	/*
	 * 其他途径发表的日志
	 */
	TYPE_OTHER,	
	/*
	 * wap发表的日志
	 */
	TYPE_WAP;	
}
