/**
 * Autogenerated by renren-api2-generator 2013-06-13 09:10:08
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
import java.util.*;
/**
 *
 * 签到的结果
 */
public class CheckinResponse {
	
	/**
	 * 操作结果 成功=0
	 */
	private int code;
	/**
	 * 提示内容
	 */
	private String message;
	public void setCode(int code) {
		this.code = code;
	}
	public int getCode() {
		return this.code;
	}
	public void setMessage(String message) {
		this.message = message;
	}
	public String getMessage() {
		return this.message;
	}
}
