/**
 * Autogenerated by renren-api2-generator 2013-03-13 15:27:21
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
/**
 * 评论的类型。
 */
 public enum CommentType {
	/*
	 * 分享
	 */
	SHARE,	
	/*
	 * 相册
	 */
	ALBUM,	
	/*
	 * 新鲜事
	 */
	FEED,	
	/*
	 * 日志
	 */
	BLOG,	
	/*
	 * 状态
	 */
	STATUS,	
	/*
	 * 照片
	 */
	PHOTO;	
}
