/**
 * Autogenerated by renren-api2-generator 2013-06-06 15:02:04
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
/**
 * 评论的类型。
 */
 public enum CommentType {
	/*
	 * 分享
	 */
	SHARE,	
	/*
	 * 相册
	 */
	ALBUM,	
	/*
	 * 日志
	 */
	BLOG,	
	/*
	 * 状态
	 */
	STATUS,	
	/*
	 * 照片
	 */
	PHOTO;	
}
