/**
 * Autogenerated by renren-api2-generator 2013-11-21 17:47:04
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
import java.util.*;
/**
 *
 * 优惠券
 */
public class CouponResponse {
	
	/**
	 * 优惠券类型
	 */
	private int couponType;
	/**
	 * 原价
	 */
	private String originalPrice;
	/**
	 * 现价
	 */
	private String currentPrice;
	/**
	 * 节省
	 */
	private String spare;
	/**
	 * 优惠内容
	 */
	private String discount;
	public void setCouponType(int couponType) {
		this.couponType = couponType;
	}
	public int getCouponType() {
		return this.couponType;
	}
	public void setOriginalPrice(String originalPrice) {
		this.originalPrice = originalPrice;
	}
	public String getOriginalPrice() {
		return this.originalPrice;
	}
	public void setCurrentPrice(String currentPrice) {
		this.currentPrice = currentPrice;
	}
	public String getCurrentPrice() {
		return this.currentPrice;
	}
	public void setSpare(String spare) {
		this.spare = spare;
	}
	public String getSpare() {
		return this.spare;
	}
	public void setDiscount(String discount) {
		this.discount = discount;
	}
	public String getDiscount() {
		return this.discount;
	}
}
