/**
 * Autogenerated by renren-api2-generator 2013-07-05 11:01:59
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
/**
 * 学历的类型
 */
 public enum EducationBackground {
	/*
	 * 博士
	 */
	DOCTOR,	
	/*
	 * 本科
	 */
	COLLEGE,	
	/*
	 * 校工
	 */
	GVY,	
	/*
	 * 小学
	 */
	PRIMARY,	
	/*
	 * 其他
	 */
	OTHER,	
	/*
	 * 教师
	 */
	TEACHER,	
	/*
	 * 硕士
	 */
	MASTER,	
	/*
	 * 高中
	 */
	HIGHSCHOOL,	
	/*
	 * 中专技校
	 */
	TECHNICAL,	
	/*
	 * 初中
	 */
	JUNIOR,	
	/*
	 * 保密
	 */
	SECRET;	
}
