/**
 * Autogenerated by renren-api2-generator 2014-04-16 15:13:50
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
/**
 * 感情状态
 */
 public enum EmotionalState {
	/*
	 * 恋爱中
	 */
	INLOVE,	
	/*
	 * 其他
	 */
	OTHER,	
	/*
	 * 单身
	 */
	SINGLE,	
	/*
	 * 已婚
	 */
	MARRIED,	
	/*
	 * 暗恋
	 */
	UNOBVIOUSLOVE,	
	/*
	 * 离异
	 */
	DIVORCE,	
	/*
	 * 订婚
	 */
	ENGAGE,	
	/*
	 * 失恋
	 */
	OUTLOVE;	
}
