/**
 * Autogenerated by renren-api2-generator 2014-04-23 18:03:22
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;

import java.io.File;
import java.util.*;

import com.renren.api.AccessToken;
import com.renren.api.ObjectMappingException;
import com.renren.api.RennException;
import com.renren.api.RennExecutor;
import com.renren.api.RennParam;
import com.renren.api.RennRequest;
import com.renren.api.RennRequest.Method;
import com.renren.api.RennResponse;
import com.renren.api.mapper.JsonMappingException;
import com.renren.api.mapper.ObjectMapper;

public class EvaluationService {
	private RennExecutor executor;

    private AccessToken token;

    private ObjectMapper mapper;
	
    /**
     * @param executor
     * @param token
     * @param mapper
     */
    public EvaluationService(RennExecutor executor, AccessToken token, ObjectMapper mapper) {
        super();
        this.executor = executor;
        this.token = token;
        this.mapper = mapper;
    }

    /**
     * 用户发表点评
     * @param content 评价内容
     * @param placeId 地点id
     * @return Long 成功时ugcid签到结果 -1=操作被拒绝，-2=含敏感信息，-3=操作太快
     * @throws   RennException 
     * SERVICE_UNAVALIALABLE 服务端临时不可用 
     * OPERATE_TOO_FAST 操作太快 
     * INVALID_CONTENT 包含敏感词 
     * OPERATION_DENY 操作被拒绝 
     * CONTENT_LENGTH_OVER_240 内容长度超过240 
     */
    public Long putEvaluation (String  content, String  placeId) throws RennException {
        Map<String, String> textParams = new HashMap<String, String>();
        if (content != null) {
	    textParams.put("content", content);
        }
        if (placeId != null) {
	    textParams.put("placeId", placeId);
        }
        Map<String, String> bodyParams = new HashMap<String, String>();
        Map<String, File[]> fileParams = new HashMap<String, File[]>();
        RennRequest request = new RennRequest("/v2/evaluation/put", Method.POST, textParams, bodyParams, fileParams, token);
        RennResponse response = executor.execute(request);
        try {
            return (Long)mapper.mapCommon(response.getResponse().toString(), Long.class);
        } catch (JsonMappingException e) {
            throw new ObjectMappingException();
        }
    }
    /**
     * 回复点评
     * @param content 回复内容
     * @param evaluationId 签到id
     * @param ownerId evaluation属于哪个用户
     * @param reId 回复哪个用户
     * @return ReplyCheckinResponse 回复签到结果
     * @throws   RennException 
     * REPLY_USER_INVALID 回复对象非法 
     * SERVICE_UNAVALIALABLE 服务端临时不可用 
     * INVALID_CONTENT 内容包含敏感词 
     * CONTENT_LENGTH_OVER_140 内容长度超过140 
     * INVALID_REPLY_SELF 不能回复自己 
     * REPLY_FAIL 回复失败 
     * EVALUATION_ID_INVALID 点评ID不存在或已删除 
     * POST_TOO_FAST 短时间回复过多 
     * CONTENT_CAN_NOT_BE_EMPTY 回复内容不能为空 
     * REPLY_USER_NOT_IN_LIST 回复对象不在回复列表中 
     */
    public ReplyCheckinResponse putEvaluationReply (String  content, Long  evaluationId, Long  ownerId, Long  reId) throws RennException {
        Map<String, String> textParams = new HashMap<String, String>();
        if (content != null) {
	    textParams.put("content", content);
        }
        if (evaluationId != null) {
            textParams.put("evaluationId", RennParam.asString(evaluationId));
        }
        if (ownerId != null) {
            textParams.put("ownerId", RennParam.asString(ownerId));
        }
        if (reId != null) {
            textParams.put("reId", RennParam.asString(reId));
        }
        Map<String, String> bodyParams = new HashMap<String, String>();
        Map<String, File[]> fileParams = new HashMap<String, File[]>();
        RennRequest request = new RennRequest("/v2/evaluation/reply/put", Method.POST, textParams, bodyParams, fileParams, token);
        RennResponse response = executor.execute(request);
        try {
            return (ReplyCheckinResponse)mapper.mapCommon(response.getResponse().toString(), ReplyCheckinResponse.class);
        } catch (JsonMappingException e) {
            throw new ObjectMappingException();
        }
    }
    /**
     * 签到回复列表
     * @param evaluationId 签到id
     * @param ownerId 评价所属人的id
     * @param pageNo 页码
     * @param pageSize 页大小
     * @return ReplyEvaluation 评价回复
     * @throws   RennException 
     * SERVICE_UNAVALIALABLE 服务端临时不可用 
     * REPLY_NOT_EXIST 回复不存在 
     * PAGESIZE_NOT_IN_RANGE 页面大小不再1-100范围内 
     * PAGE_NUMBER_MUST_LARGER_0 页码必需大于0 
     */
    public ReplyEvaluation [] listEvaluationReply (Long  evaluationId, Long  ownerId, Integer  pageNo, Integer  pageSize) throws RennException {
        Map<String, String> textParams = new HashMap<String, String>();
        if (evaluationId != null) {
            textParams.put("evaluationId", RennParam.asString(evaluationId));
        }
        if (ownerId != null) {
            textParams.put("ownerId", RennParam.asString(ownerId));
        }
        if (pageNo != null) {
            textParams.put("pageNo", RennParam.asString(pageNo));
        }
        if (pageSize != null) {
            textParams.put("pageSize", RennParam.asString(pageSize));
        }
        Map<String, String> bodyParams = new HashMap<String, String>();
        Map<String, File[]> fileParams = new HashMap<String, File[]>();
        RennRequest request = new RennRequest("/v2/evaluation/reply/list", Method.GET, textParams, bodyParams, fileParams, token);
        RennResponse response = executor.execute(request);
        try {
            return (ReplyEvaluation [])mapper.mapCommon(response.getResponse().toString(), ReplyEvaluation.class);
        } catch (JsonMappingException e) {
            throw new ObjectMappingException();
        }
    }
}
