/**
 * Autogenerated by renren-api2-generator 2014-04-23 18:03:22
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
/**
 * 新鲜事附加内容类型
 */
 public enum FeedAttachmentType {
	/*
	 * 链接
	 */
	LINK,	
	/*
	 * 相册
	 */
	ALBUM,	
	/*
	 * 日志
	 */
	BLOG,	
	/*
	 * 视频
	 */
	VIDEO,	
	/*
	 * 状态
	 */
	STATUS,	
	/*
	 * 图片
	 */
	PHOTO;	
}
