/**
 * Autogenerated by renren-api2-generator 2014-04-23 18:03:22
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
import java.util.*;
/**
 *
 * 新鲜事
 */
public class Feed {
	
	/**
	 * 新鲜事的id
	 */
	private long id;
	/**
	 * 新鲜事类型
	 */
	private FeedType type;
	/**
	 * 新鲜事触发时间
	 */
	private String time;
	/**
	 * 触发新鲜事的用户,用户对象中只有id name avatar 字段有效，其他字段无效
	 */
	private User sourceUser;
	/**
	 * 新鲜事内容
	 */
	private String message;
	/**
	 * 新鲜事中包含的缩略图
	 */
	private String thumbnailUrl;
	/**
	 * 新鲜事中包含的资源
	 */
	private FeedResource resource;
	/**
	 * 新鲜事中的附加内容
	 */
	private List<FeedAttachment> attachment;
	/**
	 * 新鲜事来源
	 */
	private Source source;
	/**
	 * lbs信息
	 */
	private Lbs lbs;
	/**
	 * 新鲜事评论列表，只返回第一条及最后一条
	 */
	private List<FeedComment> comments;
	public void setId(long id) {
		this.id = id;
	}
	public long getId() {
		return this.id;
	}
	public void setType(FeedType type) {
		this.type = type;
	}
	public FeedType getType() {
		return this.type;
	}
	public void setTime(String time) {
		this.time = time;
	}
	public String getTime() {
		return this.time;
	}
	public void setSourceUser(User sourceUser) {
		this.sourceUser = sourceUser;
	}
	public User getSourceUser() {
		return this.sourceUser;
	}
	public void setMessage(String message) {
		this.message = message;
	}
	public String getMessage() {
		return this.message;
	}
	public void setThumbnailUrl(String thumbnailUrl) {
		this.thumbnailUrl = thumbnailUrl;
	}
	public String getThumbnailUrl() {
		return this.thumbnailUrl;
	}
	public void setResource(FeedResource resource) {
		this.resource = resource;
	}
	public FeedResource getResource() {
		return this.resource;
	}
	public void setAttachment(List<FeedAttachment> attachment) {
		this.attachment = attachment;
	}
	public List<FeedAttachment> getAttachment() {
		return this.attachment;
	}
	public void setSource(Source source) {
		this.source = source;
	}
	public Source getSource() {
		return this.source;
	}
	public void setLbs(Lbs lbs) {
		this.lbs = lbs;
	}
	public Lbs getLbs() {
		return this.lbs;
	}
	public void setComments(List<FeedComment> comments) {
		this.comments = comments;
	}
	public List<FeedComment> getComments() {
		return this.comments;
	}
}
