/**
 * Autogenerated by renren-api2-generator 2014-04-16 15:13:50
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
/**
 * 新鲜事类型
 */
 public enum FeedType {
	/*
	 * 分享视频
	 */
	SHARE_VIDEO,	
	/*
	 * 更新状态
	 */
	UPDATE_STATUS,	
	/*
	 * 发表日志
	 */
	PUBLISH_BLOG,	
	/*
	 * 上传单张照片
	 */
	PUBLISH_ONE_PHOTO,	
	/*
	 * 分享照片
	 */
	SHARE_PHOTO,	
	/*
	 * 分享相册
	 */
	SHARE_ALBUM,	
	/*
	 * 上传多张照片
	 */
	PUBLISH_MORE_PHOTO,	
	/*
	 * 分享链接
	 */
	SHARE_LINK,	
	/*
	 * 分享日志
	 */
	SHARE_BLOG,	
	/*
	 * 全部类型
	 */
	ALL;	
}
