/**
 * Autogenerated by renren-api2-generator 2013-11-21 17:47:03
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
import java.util.*;
/**
 *
 * 讨论区
 */
public class ForumStat {
	
	/**
	 * thread ID
	 */
	private long threadId;
	/**
	 * 作者ID
	 */
	private long authorId;
	/**
	 * 浏览次数
	 */
	private int viewCount;
	/**
	 * 分享次数
	 */
	private int shareCount;
	/**
	 * 分享用户id列表
	 */
	private List<Long> shareUserIds;
	/**
	 * 评论次数
	 */
	private int commentCount;
	/**
	 * 评论用户列表
	 */
	private List<Long> commentUserIds;
	public void setThreadId(long threadId) {
		this.threadId = threadId;
	}
	public long getThreadId() {
		return this.threadId;
	}
	public void setAuthorId(long authorId) {
		this.authorId = authorId;
	}
	public long getAuthorId() {
		return this.authorId;
	}
	public void setViewCount(int viewCount) {
		this.viewCount = viewCount;
	}
	public int getViewCount() {
		return this.viewCount;
	}
	public void setShareCount(int shareCount) {
		this.shareCount = shareCount;
	}
	public int getShareCount() {
		return this.shareCount;
	}
	public void setShareUserIds(List<Long> shareUserIds) {
		this.shareUserIds = shareUserIds;
	}
	public List<Long> getShareUserIds() {
		return this.shareUserIds;
	}
	public void setCommentCount(int commentCount) {
		this.commentCount = commentCount;
	}
	public int getCommentCount() {
		return this.commentCount;
	}
	public void setCommentUserIds(List<Long> commentUserIds) {
		this.commentUserIds = commentUserIds;
	}
	public List<Long> getCommentUserIds() {
		return this.commentUserIds;
	}
}
