/**
 * Autogenerated by renren-api2-generator 2013-11-21 17:47:03
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
/**
 * 
 */
 public enum GameShareType {
	/*
	 * 炫耀
	 */
	MSG_SHARE_MOMENT_BEST_SCORE,	
	/*
	 * 邀请类型
	 */
	MSG_INVITE,	
	/*
	 * 礼物类型
	 */
	MSG_GIFT;	
}
