/**
 * Autogenerated by renren-api2-generator 2013-11-21 17:47:04
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
import java.util.*;
/**
 *
 * 团购信息
 */
public class GroupBuyResponse {
	
	/**
	 * 团购类型
	 */
	private int groupbuyType;
	/**
	 * 原价
	 */
	private String originalPrice;
	/**
	 * 现价
	 */
	private String currentPrice;
	/**
	 * 最高购买数量
	 */
	private int maxQuota;
	/**
	 * 最低购买数量
	 */
	private int minQuota;
	/**
	 * 当前购买数量
	 */
	private long boughtCount;
	/**
	 * 折扣
	 */
	private double rate;
	/**
	 * 节省
	 */
	private String spare;
	public void setGroupbuyType(int groupbuyType) {
		this.groupbuyType = groupbuyType;
	}
	public int getGroupbuyType() {
		return this.groupbuyType;
	}
	public void setOriginalPrice(String originalPrice) {
		this.originalPrice = originalPrice;
	}
	public String getOriginalPrice() {
		return this.originalPrice;
	}
	public void setCurrentPrice(String currentPrice) {
		this.currentPrice = currentPrice;
	}
	public String getCurrentPrice() {
		return this.currentPrice;
	}
	public void setMaxQuota(int maxQuota) {
		this.maxQuota = maxQuota;
	}
	public int getMaxQuota() {
		return this.maxQuota;
	}
	public void setMinQuota(int minQuota) {
		this.minQuota = minQuota;
	}
	public int getMinQuota() {
		return this.minQuota;
	}
	public void setBoughtCount(long boughtCount) {
		this.boughtCount = boughtCount;
	}
	public long getBoughtCount() {
		return this.boughtCount;
	}
	public void setRate(double rate) {
		this.rate = rate;
	}
	public double getRate() {
		return this.rate;
	}
	public void setSpare(String spare) {
		this.spare = spare;
	}
	public String getSpare() {
		return this.spare;
	}
}
