/**
 * Autogenerated by renren-api2-generator 2013-07-05 11:01:58
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
/**
 * 应用图标大小的枚举。
 */
 public enum IconSize {
	/*
	 * 75pt x 75pt
	 */
	MAIN,	
	/*
	 * 16pt x 16pt
	 */
	TINY,	
	/*
	 * 100pt x 100pt
	 */
	LARGE,	
	/*
	 * 48pt x 48pt
	 */
	SMALL;	
}
