/**
 * Autogenerated by renren-api2-generator 2014-04-23 18:03:22
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
/**
 * 图片大小的枚举。
 */
 public enum ImageSize {
	/*
	 * 200pt x 600pt
	 */
	MAIN,	
	/*
	 * 50pt x 50pt
	 */
	TINY,	
	/*
	 * 720pt x 720pt
	 */
	LARGE,	
	/*
	 * 100pt x 300pt
	 */
	HEAD;	
}
