/**
 * Autogenerated by renren-api2-generator 2013-07-05 11:01:59
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
import java.util.*;
/**
 *
 * 图片
 */
public class Image {
	
	/**
	 * 图片的大小。
	 */
	private ImageSize size;
	/**
	 * 图片的URL
	 */
	private String url;
	public void setSize(ImageSize size) {
		this.size = size;
	}
	public ImageSize getSize() {
		return this.size;
	}
	public void setUrl(String url) {
		this.url = url;
	}
	public String getUrl() {
		return this.url;
	}
}
