/**
 * Autogenerated by renren-api2-generator 2013-03-13 15:27:21
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
import java.util.*;
/**
 *
 * 行业
 */
public class Industry {
	
	/**
	 * 行业类别
	 */
	private String industryCategory;
	/**
	 * 行业详情
	 */
	private String industryDetail;
	public void setIndustryCategory(String industryCategory) {
		this.industryCategory = industryCategory;
	}
	public String getIndustryCategory() {
		return this.industryCategory;
	}
	public void setIndustryDetail(String industryDetail) {
		this.industryDetail = industryDetail;
	}
	public String getIndustryDetail() {
		return this.industryDetail;
	}
}
