/**
 * Autogenerated by renren-api2-generator 2013-11-21 17:47:04
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
/**
 * 发送邀请或礼物的类型
 */
 public enum InvitationType {
	/*
	 * 发送礼物
	 */
	GIFT,	
	/*
	 * 应用安装邀请
	 */
	INVITATION;	
}
