/**
 * Autogenerated by renren-api2-generator 2013-06-06 15:02:05
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
import java.util.*;
/**
 *
 * 职位
 */
public class Job {
	
	/**
	 * 职位类别
	 */
	private String jobCategory;
	/**
	 * 职位详情
	 */
	private String jobDetail;
	public void setJobCategory(String jobCategory) {
		this.jobCategory = jobCategory;
	}
	public String getJobCategory() {
		return this.jobCategory;
	}
	public void setJobDetail(String jobDetail) {
		this.jobDetail = jobDetail;
	}
	public String getJobDetail() {
		return this.jobDetail;
	}
}
