/**
 * Autogenerated by renren-api2-generator 2013-03-23 13:10:03
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
/**
 * 兴趣的类型
 */
 public enum LikeCatagory {
	/*
	 * 运动
	 */
	SPORT,	
	/*
	 * 电影
	 */
	MOVIE,	
	/*
	 * 动漫
	 */
	CARTOON,	
	/*
	 * 游戏
	 */
	GAME,	
	/*
	 * 音乐
	 */
	MUSIC,	
	/*
	 * 书籍
	 */
	BOOK,	
	/*
	 * 爱好
	 */
	INTEREST;	
}
