/**
 * Autogenerated by renren-api2-generator 2014-04-23 18:03:22
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
import java.util.*;
/**
 *
 * 获取资源被喜欢的信息，包括喜欢数、当前用户是否喜欢
 */
public class LikeInfo {
	
	/**
	 * ugc的Id
	 */
	private long ugcId;
	/**
	 * 当前用户ID
	 */
	private long userId;
	/**
	 * 资源被喜欢的数量
	 */
	private long likeCount;
	/**
	 * 当前用户是否赞了这个资源
	 */
	private boolean liked;
	/**
	 * 赞了这个资源的用户列表
	 */
	private List<User> likeUsers;
	public void setUgcId(long ugcId) {
		this.ugcId = ugcId;
	}
	public long getUgcId() {
		return this.ugcId;
	}
	public void setUserId(long userId) {
		this.userId = userId;
	}
	public long getUserId() {
		return this.userId;
	}
	public void setLikeCount(long likeCount) {
		this.likeCount = likeCount;
	}
	public long getLikeCount() {
		return this.likeCount;
	}
	public void setLiked(boolean liked) {
		this.liked = liked;
	}
	public boolean getLiked() {
		return this.liked;
	}
	public void setLikeUsers(List<User> likeUsers) {
		this.likeUsers = likeUsers;
	}
	public List<User> getLikeUsers() {
		return this.likeUsers;
	}
}
