/**
 * Autogenerated by renren-api2-generator 2014-04-23 18:03:22
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
/**
 * 
 */
 public enum LikeUGCType {
	/*
	 * 视频类型
	 */
	TYPE_VIDEO,	
	/*
	 * 日志类型
	 */
	TYPE_BLOG,	
	/*
	 * 照片类型
	 */
	TYPE_PHOTO,	
	/*
	 * 状态类型
	 */
	TYPE_STATUS,	
	/*
	 * 分享类型
	 */
	TYPE_SHARE,	
	/*
	 * 相册类型
	 */
	TYPE_ALBUM;	
}
