/**
 * Autogenerated by renren-api2-generator 2013-11-21 17:47:04
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
import java.util.*;
/**
 *
 * 地点新鲜事中包含的照片信息
 */
public class LocationPhoto {
	
	/**
	 * 照片ID
	 */
	private long photoId;
	/**
	 * 相册ID
	 */
	private long albumId;
	/**
	 * 照片描述
	 */
	private String description;
	/**
	 * 照片对应的各种类型图片
	 */
	private List<Image> images;
	public void setPhotoId(long photoId) {
		this.photoId = photoId;
	}
	public long getPhotoId() {
		return this.photoId;
	}
	public void setAlbumId(long albumId) {
		this.albumId = albumId;
	}
	public long getAlbumId() {
		return this.albumId;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public String getDescription() {
		return this.description;
	}
	public void setImages(List<Image> images) {
		this.images = images;
	}
	public List<Image> getImages() {
		return this.images;
	}
}
