/**
 * Autogenerated by renren-api2-generator 2013-07-05 11:01:58
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
import java.util.*;
/**
 *
 * 定位的地点。
 */
public class Location {
	
	/**
	 * 国家
	 */
	private String nation;
	/**
	 * 省份或直辖市
	 */
	private String province;
	/**
	 * 城市
	 */
	private String city;
	/**
	 * 城市代码
	 */
	private String cityCode;
	/**
	 * 区、县
	 */
	private String county;
	/**
	 * 最近的街道名称
	 */
	private String streetName;
	/**
	 * 定位的地址
	 */
	private String address;
	/**
	 * 实际经度
	 */
	private double longitude;
	/**
	 * 实际维度
	 */
	private double latitude;
	public void setNation(String nation) {
		this.nation = nation;
	}
	public String getNation() {
		return this.nation;
	}
	public void setProvince(String province) {
		this.province = province;
	}
	public String getProvince() {
		return this.province;
	}
	public void setCity(String city) {
		this.city = city;
	}
	public String getCity() {
		return this.city;
	}
	public void setCityCode(String cityCode) {
		this.cityCode = cityCode;
	}
	public String getCityCode() {
		return this.cityCode;
	}
	public void setCounty(String county) {
		this.county = county;
	}
	public String getCounty() {
		return this.county;
	}
	public void setStreetName(String streetName) {
		this.streetName = streetName;
	}
	public String getStreetName() {
		return this.streetName;
	}
	public void setAddress(String address) {
		this.address = address;
	}
	public String getAddress() {
		return this.address;
	}
	public void setLongitude(double longitude) {
		this.longitude = longitude;
	}
	public double getLongitude() {
		return this.longitude;
	}
	public void setLatitude(double latitude) {
		this.latitude = latitude;
	}
	public double getLatitude() {
		return this.latitude;
	}
}
