/**
 * Autogenerated by renren-api2-generator 2013-07-05 11:01:59
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
/**
 * 
 */
 public enum LocationFeedType {
	/*
	 * 全部类型
	 */
	TYPE_ALL,	
	/*
	 * 照片类型
	 */
	TYPE_IMAGE,	
	/*
	 * 签到类型
	 */
	TYPE_CHECKIN,	
	/*
	 * 状态类型
	 */
	TYPE_STATUS,	
	/*
	 * 地点评价类型
	 */
	TYPE_POINT;	
}
