/**
 * Autogenerated by renren-api2-generator 2013-11-21 17:47:03
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
/**
 * 
 */
 public enum MessageType {
	/*
	 * 游戏类型
	 */
	TYPE_GAME_SHARE,	
	/*
	 * 图片+文本
	 */
	TYPE_PHOTO_AND_TEXT,	
	/*
	 * 照片类型
	 */
	TYPE_PHOTO,	
	/*
	 * 文本类型
	 */
	TYPE_TEXT;	
}
