/**
 * Autogenerated by renren-api2-generator 2013-11-21 17:47:04
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
/**
 * 消息类型
 */
 public enum NewsType {
	/*
	 * 新鲜事
	 */
	FEED,	
	/*
	 * 提醒
	 */
	REMIND,	
	/*
	 * 通知
	 */
	NOTIFICATION,	
	/*
	 * 请求
	 */
	REQUEST,	
	/*
	 * 所有类型
	 */
	ALL;	
}
