/**
 * Autogenerated by renren-api2-generator 2013-11-21 17:47:04
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
import java.util.*;
/**
 *
 * 消息数
 */
public class NewsCounts {
	
	/**
	 * 未读通知数
	 */
	private int notificationCount;
	/**
	 * 未读提醒数
	 */
	private int remindCount;
	/**
	 * 好友请求数
	 */
	private int requestCount;
	/**
	 * 未读新鲜事数
	 */
	private int feedCount;
	public void setNotificationCount(int notificationCount) {
		this.notificationCount = notificationCount;
	}
	public int getNotificationCount() {
		return this.notificationCount;
	}
	public void setRemindCount(int remindCount) {
		this.remindCount = remindCount;
	}
	public int getRemindCount() {
		return this.remindCount;
	}
	public void setRequestCount(int requestCount) {
		this.requestCount = requestCount;
	}
	public int getRequestCount() {
		return this.requestCount;
	}
	public void setFeedCount(int feedCount) {
		this.feedCount = feedCount;
	}
	public int getFeedCount() {
		return this.feedCount;
	}
}
