/**
 * Autogenerated by renren-api2-generator 2014-04-23 18:03:22
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
import java.util.*;
/**
 *
 * Page的信息
 */
public class PageInfo {
	
	/**
	 * pageid
	 */
	private int id;
	/**
	 * page名称
	 */
	private String name;
	/**
	 * 别名
	 */
	private String pagealias;
	/**
	 * 自我介绍
	 */
	private String description;
	/**
	 * 创建者id
	 */
	private int ownerId;
	/**
	 * 年龄限制
	 */
	private int ageRestriction;
	/**
	 * 创建时间
	 */
	private String createTime;
	/**
	 * 粉丝数
	 */
	private int fansCount;
	/**
	 * 小头像
	 */
	private String tinyUrl;
	/**
	 * 头像
	 */
	private String headUrl;
	/**
	 * 头图
	 */
	private String mainUrl;
	/**
	 * 原图
	 */
	private String largeUrl;
	/**
	 * 等级
	 */
	private int level;
	public void setId(int id) {
		this.id = id;
	}
	public int getId() {
		return this.id;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getName() {
		return this.name;
	}
	public void setPagealias(String pagealias) {
		this.pagealias = pagealias;
	}
	public String getPagealias() {
		return this.pagealias;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public String getDescription() {
		return this.description;
	}
	public void setOwnerId(int ownerId) {
		this.ownerId = ownerId;
	}
	public int getOwnerId() {
		return this.ownerId;
	}
	public void setAgeRestriction(int ageRestriction) {
		this.ageRestriction = ageRestriction;
	}
	public int getAgeRestriction() {
		return this.ageRestriction;
	}
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}
	public String getCreateTime() {
		return this.createTime;
	}
	public void setFansCount(int fansCount) {
		this.fansCount = fansCount;
	}
	public int getFansCount() {
		return this.fansCount;
	}
	public void setTinyUrl(String tinyUrl) {
		this.tinyUrl = tinyUrl;
	}
	public String getTinyUrl() {
		return this.tinyUrl;
	}
	public void setHeadUrl(String headUrl) {
		this.headUrl = headUrl;
	}
	public String getHeadUrl() {
		return this.headUrl;
	}
	public void setMainUrl(String mainUrl) {
		this.mainUrl = mainUrl;
	}
	public String getMainUrl() {
		return this.mainUrl;
	}
	public void setLargeUrl(String largeUrl) {
		this.largeUrl = largeUrl;
	}
	public String getLargeUrl() {
		return this.largeUrl;
	}
	public void setLevel(int level) {
		this.level = level;
	}
	public int getLevel() {
		return this.level;
	}
}
