/**
 * Autogenerated by renren-api2-generator 2013-11-21 17:47:03
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
import java.util.*;
/**
 *
 * 评论
 */
public class PageComment {
	
	/**
	 * 评论ID
	 */
	private long id;
	/**
	 * ugcID
	 */
	private long ugcId;
	/**
	 * ugc类型
	 */
	private PageUgcType ugcType;
	/**
	 * 评论内容
	 */
	private String content;
	/**
	 * 评论用户的ID
	 */
	private long authorId;
	/**
	 * 评论用户的姓名
	 */
	private String authorName;
	/**
	 * 评论用户头像
	 */
	private String headUrl;
	/**
	 * 评论时间
	 */
	private String time;
	public void setId(long id) {
		this.id = id;
	}
	public long getId() {
		return this.id;
	}
	public void setUgcId(long ugcId) {
		this.ugcId = ugcId;
	}
	public long getUgcId() {
		return this.ugcId;
	}
	public void setUgcType(PageUgcType ugcType) {
		this.ugcType = ugcType;
	}
	public PageUgcType getUgcType() {
		return this.ugcType;
	}
	public void setContent(String content) {
		this.content = content;
	}
	public String getContent() {
		return this.content;
	}
	public void setAuthorId(long authorId) {
		this.authorId = authorId;
	}
	public long getAuthorId() {
		return this.authorId;
	}
	public void setAuthorName(String authorName) {
		this.authorName = authorName;
	}
	public String getAuthorName() {
		return this.authorName;
	}
	public void setHeadUrl(String headUrl) {
		this.headUrl = headUrl;
	}
	public String getHeadUrl() {
		return this.headUrl;
	}
	public void setTime(String time) {
		this.time = time;
	}
	public String getTime() {
		return this.time;
	}
}
