/**
 * Autogenerated by renren-api2-generator 2013-11-21 17:47:03
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
/**
 * Page的UGC类型。
 */
 public enum PageUgcType {
	/*
	 * 相册
	 */
	ALBUM,	
	/*
	 * 日志
	 */
	BLOG,	
	/*
	 * 视频
	 */
	VIDEO,	
	/*
	 * 状态
	 */
	STATUS,	
	/*
	 * 讨论组
	 */
	FORUM,	
	/*
	 * 照片
	 */
	PHOTO;	
}
