/**
 * Autogenerated by renren-api2-generator 2013-11-21 17:47:03
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
import java.util.*;
/**
 *
 * 公共主页分享的视频
 */
public class PageVideo {
	
	/**
	 * 视频的ID
	 */
	private long id;
	/**
	 * 分享次数
	 */
	private long shareCount;
	/**
	 * 分享的用户ID列表
	 */
	private List<Long> userIdList;
	/**
	 * 评论次数
	 */
	private long commentCount;
	public void setId(long id) {
		this.id = id;
	}
	public long getId() {
		return this.id;
	}
	public void setShareCount(long shareCount) {
		this.shareCount = shareCount;
	}
	public long getShareCount() {
		return this.shareCount;
	}
	public void setUserIdList(List<Long> userIdList) {
		this.userIdList = userIdList;
	}
	public List<Long> getUserIdList() {
		return this.userIdList;
	}
	public void setCommentCount(long commentCount) {
		this.commentCount = commentCount;
	}
	public long getCommentCount() {
		return this.commentCount;
	}
}
