/**
 * Autogenerated by renren-api2-generator 2013-11-21 17:47:03
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
import java.util.*;
/**
 *
 * 公共主页分享
 */
public class PageShare {
	
	/**
	 * 分享的ID
	 */
	private long id;
	/**
	 * 分享内容
	 */
	private String content;
	/**
	 * 分享时间
	 */
	private String time;
	/**
	 * 分享次数
	 */
	private int shareNumber;
	/**
	 * 评论次数
	 */
	private int commentNumber;
	public void setId(long id) {
		this.id = id;
	}
	public long getId() {
		return this.id;
	}
	public void setContent(String content) {
		this.content = content;
	}
	public String getContent() {
		return this.content;
	}
	public void setTime(String time) {
		this.time = time;
	}
	public String getTime() {
		return this.time;
	}
	public void setShareNumber(int shareNumber) {
		this.shareNumber = shareNumber;
	}
	public int getShareNumber() {
		return this.shareNumber;
	}
	public void setCommentNumber(int commentNumber) {
		this.commentNumber = commentNumber;
	}
	public int getCommentNumber() {
		return this.commentNumber;
	}
}
