/**
 * Autogenerated by renren-api2-generator 2013-07-05 11:01:59
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
import java.util.*;
/**
 *
 * 照片
 */
public class Photo {
	
	/**
	 * 照片的ID
	 */
	private long id;
	/**
	 * 照片所属相册的ID
	 */
	private long albumId;
	/**
	 * 照片所有者的ID
	 */
	private long ownerId;
	/**
	 * 照片的描述
	 */
	private String description;
	/**
	 * 照片对应的各种类型图片
	 */
	private List<Image> images;
	/**
	 * 照片的创建时间
	 */
	private String createTime;
	/**
	 * 照片被浏览的次数
	 */
	private int viewCount;
	/**
	 * 照片被回复的次数
	 */
	private int commentCount;
	public void setId(long id) {
		this.id = id;
	}
	public long getId() {
		return this.id;
	}
	public void setAlbumId(long albumId) {
		this.albumId = albumId;
	}
	public long getAlbumId() {
		return this.albumId;
	}
	public void setOwnerId(long ownerId) {
		this.ownerId = ownerId;
	}
	public long getOwnerId() {
		return this.ownerId;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public String getDescription() {
		return this.description;
	}
	public void setImages(List<Image> images) {
		this.images = images;
	}
	public List<Image> getImages() {
		return this.images;
	}
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}
	public String getCreateTime() {
		return this.createTime;
	}
	public void setViewCount(int viewCount) {
		this.viewCount = viewCount;
	}
	public int getViewCount() {
		return this.viewCount;
	}
	public void setCommentCount(int commentCount) {
		this.commentCount = commentCount;
	}
	public int getCommentCount() {
		return this.commentCount;
	}
}
