/**
 * Autogenerated by renren-api2-generator 2013-11-21 17:47:04
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
import java.util.*;
/**
 *
 * 城市信息用于查询
 */
public class PlaceCityInfoResponse {
	
	/**
	 * 区号
	 */
	private String city_code;
	/**
	 * 城市名
	 */
	private String city_name;
	/**
	 * 省份
	 */
	private String province;
	public void setCity_code(String city_code) {
		this.city_code = city_code;
	}
	public String getCity_code() {
		return this.city_code;
	}
	public void setCity_name(String city_name) {
		this.city_name = city_name;
	}
	public String getCity_name() {
		return this.city_name;
	}
	public void setProvince(String province) {
		this.province = province;
	}
	public String getProvince() {
		return this.province;
	}
}
