/**
 * Autogenerated by renren-api2-generator 2014-04-23 18:03:22
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
import java.util.*;
/**
 *
 * 地点信息
 */
public class Place {
	
	/**
	 * 地点的ID
	 */
	private String placeId;
	/**
	 * 经度
	 */
	private double longitude;
	/**
	 * 纬度
	 */
	private double latitude;
	/**
	 * 地点的名称
	 */
	private String name;
	/**
	 * 地点的地址
	 */
	private String address;
	/**
	 * 地点的电话
	 */
	private String phone;
	/**
	 * 地点所在国家
	 */
	private String country;
	/**
	 * 地点所在省或直辖市
	 */
	private String province;
	/**
	 * 地点所在市
	 */
	private String city;
	/**
	 * 地点的区号
	 */
	private String cityCode;
	/**
	 * 地点所在区
	 */
	private String district;
	/**
	 * 地点所在街道
	 */
	private String street;
	public void setPlaceId(String placeId) {
		this.placeId = placeId;
	}
	public String getPlaceId() {
		return this.placeId;
	}
	public void setLongitude(double longitude) {
		this.longitude = longitude;
	}
	public double getLongitude() {
		return this.longitude;
	}
	public void setLatitude(double latitude) {
		this.latitude = latitude;
	}
	public double getLatitude() {
		return this.latitude;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getName() {
		return this.name;
	}
	public void setAddress(String address) {
		this.address = address;
	}
	public String getAddress() {
		return this.address;
	}
	public void setPhone(String phone) {
		this.phone = phone;
	}
	public String getPhone() {
		return this.phone;
	}
	public void setCountry(String country) {
		this.country = country;
	}
	public String getCountry() {
		return this.country;
	}
	public void setProvince(String province) {
		this.province = province;
	}
	public String getProvince() {
		return this.province;
	}
	public void setCity(String city) {
		this.city = city;
	}
	public String getCity() {
		return this.city;
	}
	public void setCityCode(String cityCode) {
		this.cityCode = cityCode;
	}
	public String getCityCode() {
		return this.cityCode;
	}
	public void setDistrict(String district) {
		this.district = district;
	}
	public String getDistrict() {
		return this.district;
	}
	public void setStreet(String street) {
		this.street = street;
	}
	public String getStreet() {
		return this.street;
	}
}
