/**
 * Autogenerated by renren-api2-generator 2013-11-21 17:47:04
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
import java.util.*;
/**
 *
 * 地点商业信息
 */
public class PlaceCommercialInfosResponse {
	
	/**
	 * 信息总数
	 */
	private int count;
	/**
	 * 具体信息内容
	 */
	private List<PoiEventCityInfoResponse> poiEventCityInfoList;
	public void setCount(int count) {
		this.count = count;
	}
	public int getCount() {
		return this.count;
	}
	public void setPoiEventCityInfoList(List<PoiEventCityInfoResponse> poiEventCityInfoList) {
		this.poiEventCityInfoList = poiEventCityInfoList;
	}
	public List<PoiEventCityInfoResponse> getPoiEventCityInfoList() {
		return this.poiEventCityInfoList;
	}
}
