/**
 * Autogenerated by renren-api2-generator 2013-11-21 17:47:04
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
import java.util.*;
/**
 *
 * 签到详情
 */
public class PoiCheckin {
	
	/**
	 * 签到id, 入库时分配
	 */
	private long id;
	/**
	 * 用户id
	 */
	private long userId;
	/**
	 * pid
	 */
	private String pid;
	/**
	 * 经度
	 */
	private double longitudeGps;
	/**
	 * 纬度
	 */
	private double latitudeGps;
	/**
	 * 签到时间
	 */
	private String addTime;
	/**
	 * 设置默认为空字符串
	 */
	private String statusText;
	/**
	 * 评论次数
	 */
	private int commentCount;
	/**
	 * 定位方式 0=手输 1=GPS 2=基站 3=ip 4=network 5=照片自带EXIF信息
	 */
	private int locateType;
	/**
	 * 来源id
	 */
	private int appId;
	public void setId(long id) {
		this.id = id;
	}
	public long getId() {
		return this.id;
	}
	public void setUserId(long userId) {
		this.userId = userId;
	}
	public long getUserId() {
		return this.userId;
	}
	public void setPid(String pid) {
		this.pid = pid;
	}
	public String getPid() {
		return this.pid;
	}
	public void setLongitudeGps(double longitudeGps) {
		this.longitudeGps = longitudeGps;
	}
	public double getLongitudeGps() {
		return this.longitudeGps;
	}
	public void setLatitudeGps(double latitudeGps) {
		this.latitudeGps = latitudeGps;
	}
	public double getLatitudeGps() {
		return this.latitudeGps;
	}
	public void setAddTime(String addTime) {
		this.addTime = addTime;
	}
	public String getAddTime() {
		return this.addTime;
	}
	public void setStatusText(String statusText) {
		this.statusText = statusText;
	}
	public String getStatusText() {
		return this.statusText;
	}
	public void setCommentCount(int commentCount) {
		this.commentCount = commentCount;
	}
	public int getCommentCount() {
		return this.commentCount;
	}
	public void setLocateType(int locateType) {
		this.locateType = locateType;
	}
	public int getLocateType() {
		return this.locateType;
	}
	public void setAppId(int appId) {
		this.appId = appId;
	}
	public int getAppId() {
		return this.appId;
	}
}
