/**
 * Autogenerated by renren-api2-generator 2013-11-21 17:47:04
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
import java.util.*;
/**
 *
 * 地点活动信息
 */
public class PoiEventDataInfo {
	
	/**
	 * 地点信息
	 */
	private PoiInfoResponse poiInfo;
	/**
	 * 事件列表
	 */
	private List<PoiEventCityInfoResponse> poiEventList;
	public void setPoiInfo(PoiInfoResponse poiInfo) {
		this.poiInfo = poiInfo;
	}
	public PoiInfoResponse getPoiInfo() {
		return this.poiInfo;
	}
	public void setPoiEventList(List<PoiEventCityInfoResponse> poiEventList) {
		this.poiEventList = poiEventList;
	}
	public List<PoiEventCityInfoResponse> getPoiEventList() {
		return this.poiEventList;
	}
}
