/**
 * Autogenerated by renren-api2-generator 2013-11-21 17:47:04
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
import java.util.*;
/**
 *
 * 根据经纬度返回的附近活动列表
 */
public class PoiEventLatLonBizInfoResponse {
	
	/**
	 * 信息总数
	 */
	private int count;
	/**
	 * poiEvent 列表
	 */
	private List<PoiEventDataInfo> poiEventDataInfoList;
	public void setCount(int count) {
		this.count = count;
	}
	public int getCount() {
		return this.count;
	}
	public void setPoiEventDataInfoList(List<PoiEventDataInfo> poiEventDataInfoList) {
		this.poiEventDataInfoList = poiEventDataInfoList;
	}
	public List<PoiEventDataInfo> getPoiEventDataInfoList() {
		return this.poiEventDataInfoList;
	}
}
