/**
 * Autogenerated by renren-api2-generator 2013-11-21 17:47:04
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
import java.util.*;
/**
 *
 * 城市活动信息
 */
public class PoiEventCityInfoResponse {
	
	/**
	 * 活动id
	 */
	private long event_id;
	/**
	 * 活动标题
	 */
	private String title;
	/**
	 * 活动类型
	 */
	private int eventType;
	/**
	 * 活动详情页web
	 */
	private String minisiteWebUrl;
	/**
	 * 活动详情页wap
	 */
	private String minisiteWapurl;
	/**
	 * 活动推广开始时间
	 */
	private String broadStartTime;
	/**
	 * 活动推广结束时间
	 */
	private String broadEndTime;
	/**
	 * 活动开始时间
	 */
	private String eventStartTime;
	/**
	 * 活动结束时间
	 */
	private String eventEndTime;
	/**
	 * 活动来源名称
	 */
	private String eventSource;
	/**
	 * 活动来源web地址
	 */
	private String eventSourceWebUrl;
	/**
	 * 活动来源wap地址
	 */
	private String eventSourceWapUrl;
	/**
	 * 活动小图地址
	 */
	private String eventMobileLogoUrl;
	/**
	 * 活动大图地址
	 */
	private String eventWebLogoUrl;
	/**
	 * 活动标签
	 */
	private String tag;
	/**
	 * 活动概述
	 */
	private String description;
	/**
	 * 预定购买下载web地址
	 */
	private String orderWebUrl;
	/**
	 * 预定购买下载wap地址
	 */
	private String orderWapUrl;
	/**
	 * 优惠券
	 */
	private CouponResponse coupon;
	/**
	 * 团购
	 */
	private GroupBuyResponse group_buy;
	/**
	 * 活动
	 */
	private ActivityResponse activity;
	/**
	 * 地点信息
	 */
	private PoiInfoResponse poi_info;
	/**
	 * 活动详情
	 */
	private String content;
	public void setEvent_id(long event_id) {
		this.event_id = event_id;
	}
	public long getEvent_id() {
		return this.event_id;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getTitle() {
		return this.title;
	}
	public void setEventType(int eventType) {
		this.eventType = eventType;
	}
	public int getEventType() {
		return this.eventType;
	}
	public void setMinisiteWebUrl(String minisiteWebUrl) {
		this.minisiteWebUrl = minisiteWebUrl;
	}
	public String getMinisiteWebUrl() {
		return this.minisiteWebUrl;
	}
	public void setMinisiteWapurl(String minisiteWapurl) {
		this.minisiteWapurl = minisiteWapurl;
	}
	public String getMinisiteWapurl() {
		return this.minisiteWapurl;
	}
	public void setBroadStartTime(String broadStartTime) {
		this.broadStartTime = broadStartTime;
	}
	public String getBroadStartTime() {
		return this.broadStartTime;
	}
	public void setBroadEndTime(String broadEndTime) {
		this.broadEndTime = broadEndTime;
	}
	public String getBroadEndTime() {
		return this.broadEndTime;
	}
	public void setEventStartTime(String eventStartTime) {
		this.eventStartTime = eventStartTime;
	}
	public String getEventStartTime() {
		return this.eventStartTime;
	}
	public void setEventEndTime(String eventEndTime) {
		this.eventEndTime = eventEndTime;
	}
	public String getEventEndTime() {
		return this.eventEndTime;
	}
	public void setEventSource(String eventSource) {
		this.eventSource = eventSource;
	}
	public String getEventSource() {
		return this.eventSource;
	}
	public void setEventSourceWebUrl(String eventSourceWebUrl) {
		this.eventSourceWebUrl = eventSourceWebUrl;
	}
	public String getEventSourceWebUrl() {
		return this.eventSourceWebUrl;
	}
	public void setEventSourceWapUrl(String eventSourceWapUrl) {
		this.eventSourceWapUrl = eventSourceWapUrl;
	}
	public String getEventSourceWapUrl() {
		return this.eventSourceWapUrl;
	}
	public void setEventMobileLogoUrl(String eventMobileLogoUrl) {
		this.eventMobileLogoUrl = eventMobileLogoUrl;
	}
	public String getEventMobileLogoUrl() {
		return this.eventMobileLogoUrl;
	}
	public void setEventWebLogoUrl(String eventWebLogoUrl) {
		this.eventWebLogoUrl = eventWebLogoUrl;
	}
	public String getEventWebLogoUrl() {
		return this.eventWebLogoUrl;
	}
	public void setTag(String tag) {
		this.tag = tag;
	}
	public String getTag() {
		return this.tag;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public String getDescription() {
		return this.description;
	}
	public void setOrderWebUrl(String orderWebUrl) {
		this.orderWebUrl = orderWebUrl;
	}
	public String getOrderWebUrl() {
		return this.orderWebUrl;
	}
	public void setOrderWapUrl(String orderWapUrl) {
		this.orderWapUrl = orderWapUrl;
	}
	public String getOrderWapUrl() {
		return this.orderWapUrl;
	}
	public void setCoupon(CouponResponse coupon) {
		this.coupon = coupon;
	}
	public CouponResponse getCoupon() {
		return this.coupon;
	}
	public void setGroup_buy(GroupBuyResponse group_buy) {
		this.group_buy = group_buy;
	}
	public GroupBuyResponse getGroup_buy() {
		return this.group_buy;
	}
	public void setActivity(ActivityResponse activity) {
		this.activity = activity;
	}
	public ActivityResponse getActivity() {
		return this.activity;
	}
	public void setPoi_info(PoiInfoResponse poi_info) {
		this.poi_info = poi_info;
	}
	public PoiInfoResponse getPoi_info() {
		return this.poi_info;
	}
	public void setContent(String content) {
		this.content = content;
	}
	public String getContent() {
		return this.content;
	}
}
