/**
 * Autogenerated by renren-api2-generator 2013-11-21 17:47:04
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
import java.util.*;
/**
 *
 * 地点信息
 */
public class PoiInfoResponse {
	
	/**
	 * 地点唯一标识
	 */
	private String pid;
	/**
	 * 地点名
	 */
	private String poiName;
	/**
	 * 地址
	 */
	private String poiAddress;
	/**
	 * 城市
	 */
	private String city;
	/**
	 * 地区
	 */
	private String district;
	/**
	 * 地点显示标题
	 */
	private String caption;
	/**
	 * 经度
	 */
	private double longitude;
	/**
	 * 维度
	 */
	private double latitude;
	/**
	 * 地点电话
	 */
	private String phone;
	/**
	 * 地点类型
	 */
	private String poiType;
	/**
	 * 地点子类型
	 */
	private String subPoiType;
	/**
	 * 描述
	 */
	private String poiDescription;
	/**
	 * 地点照片wap地址
	 */
	private String poiPhotoWapUrl;
	/**
	 * 地点照片Web地址
	 */
	private String poiPhotoWebUrl;
	/**
	 * 地点所属商圈
	 */
	private String ccp;
	/**
	 * 地点Url
	 */
	private String addressUrl;
	/**
	 * 地点Url
	 */
	private String addressWapUrl;
	/**
	 * 地点省份
	 */
	private String province;
	/**
	 * 地点国家
	 */
	private String country;
	/**
	 * 地点所在街道
	 */
	private String street;
	/**
	 * 地点邮编
	 */
	private String zip_code;
	/**
	 * 地点行政区代码
	 */
	private String administrativeCode;
	/**
	 * 地点交通路线
	 */
	private String traffic;
	/**
	 * 营业时间
	 */
	private String businessHour;
	/**
	 * 地点停车位数量
	 */
	private long stallCount;
	/**
	 * 地点是否有wifi
	 */
	private int wireless;
	/**
	 * 地点是否支持刷卡
	 */
	private String payment;
	/**
	 * 是否支持消费发票
	 */
	private int bill;
	/**
	 * 该地点活动数量
	 */
	private int eventCount;
	/**
	 * 距离查询位置的距离
	 */
	private int distance;
	public void setPid(String pid) {
		this.pid = pid;
	}
	public String getPid() {
		return this.pid;
	}
	public void setPoiName(String poiName) {
		this.poiName = poiName;
	}
	public String getPoiName() {
		return this.poiName;
	}
	public void setPoiAddress(String poiAddress) {
		this.poiAddress = poiAddress;
	}
	public String getPoiAddress() {
		return this.poiAddress;
	}
	public void setCity(String city) {
		this.city = city;
	}
	public String getCity() {
		return this.city;
	}
	public void setDistrict(String district) {
		this.district = district;
	}
	public String getDistrict() {
		return this.district;
	}
	public void setCaption(String caption) {
		this.caption = caption;
	}
	public String getCaption() {
		return this.caption;
	}
	public void setLongitude(double longitude) {
		this.longitude = longitude;
	}
	public double getLongitude() {
		return this.longitude;
	}
	public void setLatitude(double latitude) {
		this.latitude = latitude;
	}
	public double getLatitude() {
		return this.latitude;
	}
	public void setPhone(String phone) {
		this.phone = phone;
	}
	public String getPhone() {
		return this.phone;
	}
	public void setPoiType(String poiType) {
		this.poiType = poiType;
	}
	public String getPoiType() {
		return this.poiType;
	}
	public void setSubPoiType(String subPoiType) {
		this.subPoiType = subPoiType;
	}
	public String getSubPoiType() {
		return this.subPoiType;
	}
	public void setPoiDescription(String poiDescription) {
		this.poiDescription = poiDescription;
	}
	public String getPoiDescription() {
		return this.poiDescription;
	}
	public void setPoiPhotoWapUrl(String poiPhotoWapUrl) {
		this.poiPhotoWapUrl = poiPhotoWapUrl;
	}
	public String getPoiPhotoWapUrl() {
		return this.poiPhotoWapUrl;
	}
	public void setPoiPhotoWebUrl(String poiPhotoWebUrl) {
		this.poiPhotoWebUrl = poiPhotoWebUrl;
	}
	public String getPoiPhotoWebUrl() {
		return this.poiPhotoWebUrl;
	}
	public void setCcp(String ccp) {
		this.ccp = ccp;
	}
	public String getCcp() {
		return this.ccp;
	}
	public void setAddressUrl(String addressUrl) {
		this.addressUrl = addressUrl;
	}
	public String getAddressUrl() {
		return this.addressUrl;
	}
	public void setAddressWapUrl(String addressWapUrl) {
		this.addressWapUrl = addressWapUrl;
	}
	public String getAddressWapUrl() {
		return this.addressWapUrl;
	}
	public void setProvince(String province) {
		this.province = province;
	}
	public String getProvince() {
		return this.province;
	}
	public void setCountry(String country) {
		this.country = country;
	}
	public String getCountry() {
		return this.country;
	}
	public void setStreet(String street) {
		this.street = street;
	}
	public String getStreet() {
		return this.street;
	}
	public void setZip_code(String zip_code) {
		this.zip_code = zip_code;
	}
	public String getZip_code() {
		return this.zip_code;
	}
	public void setAdministrativeCode(String administrativeCode) {
		this.administrativeCode = administrativeCode;
	}
	public String getAdministrativeCode() {
		return this.administrativeCode;
	}
	public void setTraffic(String traffic) {
		this.traffic = traffic;
	}
	public String getTraffic() {
		return this.traffic;
	}
	public void setBusinessHour(String businessHour) {
		this.businessHour = businessHour;
	}
	public String getBusinessHour() {
		return this.businessHour;
	}
	public void setStallCount(long stallCount) {
		this.stallCount = stallCount;
	}
	public long getStallCount() {
		return this.stallCount;
	}
	public void setWireless(int wireless) {
		this.wireless = wireless;
	}
	public int getWireless() {
		return this.wireless;
	}
	public void setPayment(String payment) {
		this.payment = payment;
	}
	public String getPayment() {
		return this.payment;
	}
	public void setBill(int bill) {
		this.bill = bill;
	}
	public int getBill() {
		return this.bill;
	}
	public void setEventCount(int eventCount) {
		this.eventCount = eventCount;
	}
	public int getEventCount() {
		return this.eventCount;
	}
	public void setDistance(int distance) {
		this.distance = distance;
	}
	public int getDistance() {
		return this.distance;
	}
}
