/**
 * Autogenerated by renren-api2-generator 2013-07-05 11:01:59
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
import java.util.*;
/**
 *
 * 个人主页信息
 */
public class Profile {
	
	/**
	 * 用户主页来访访客数
	 */
	private int visitorCount;
	/**
	 * 用户的状态数
	 */
	private int statusCount;
	/**
	 * 用户发表的日志数
	 */
	private int blogCount;
	/**
	 * 用户的相册数
	 */
	private int albumCount;
	/**
	 * 用户的分享数
	 */
	private int shareCount;
	/**
	 * 用户喜欢的公共主页数
	 */
	private int pageCount;
	/**
	 * 用户关注的小站数
	 */
	private int zhanCount;
	/**
	 * 用户安装的应用数
	 */
	private int appCount;
	/**
	 * 用户喜欢的音乐数
	 */
	private int musicCount;
	/**
	 * 用户喜欢的电影数
	 */
	private int movieCount;
	/**
	 * 用户的照片数
	 */
	private int photoCount;
	/**
	 * 用户的好友数
	 */
	private int friendCount;
	public void setVisitorCount(int visitorCount) {
		this.visitorCount = visitorCount;
	}
	public int getVisitorCount() {
		return this.visitorCount;
	}
	public void setStatusCount(int statusCount) {
		this.statusCount = statusCount;
	}
	public int getStatusCount() {
		return this.statusCount;
	}
	public void setBlogCount(int blogCount) {
		this.blogCount = blogCount;
	}
	public int getBlogCount() {
		return this.blogCount;
	}
	public void setAlbumCount(int albumCount) {
		this.albumCount = albumCount;
	}
	public int getAlbumCount() {
		return this.albumCount;
	}
	public void setShareCount(int shareCount) {
		this.shareCount = shareCount;
	}
	public int getShareCount() {
		return this.shareCount;
	}
	public void setPageCount(int pageCount) {
		this.pageCount = pageCount;
	}
	public int getPageCount() {
		return this.pageCount;
	}
	public void setZhanCount(int zhanCount) {
		this.zhanCount = zhanCount;
	}
	public int getZhanCount() {
		return this.zhanCount;
	}
	public void setAppCount(int appCount) {
		this.appCount = appCount;
	}
	public int getAppCount() {
		return this.appCount;
	}
	public void setMusicCount(int musicCount) {
		this.musicCount = musicCount;
	}
	public int getMusicCount() {
		return this.musicCount;
	}
	public void setMovieCount(int movieCount) {
		this.movieCount = movieCount;
	}
	public int getMovieCount() {
		return this.movieCount;
	}
	public void setPhotoCount(int photoCount) {
		this.photoCount = photoCount;
	}
	public int getPhotoCount() {
		return this.photoCount;
	}
	public void setFriendCount(int friendCount) {
		this.friendCount = friendCount;
	}
	public int getFriendCount() {
		return this.friendCount;
	}
}
