/**
 * Autogenerated by renren-api2-generator 2013-11-21 17:47:03
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
import java.util.*;
/**
 *
 * 公共相册
 */
public class PublicAlbumPhoto {
	
	/**
	 * 相册的ID
	 */
	private long id;
	/**
	 * 照片ID
	 */
	private long photoId;
	/**
	 * 分享次数
	 */
	private long shareCount;
	/**
	 * 分享的用户ID列表
	 */
	private List<Long> userIdList;
	/**
	 * 投票次数
	 */
	private long voteCount;
	/**
	 * 评论次数
	 */
	private long commentCount;
	/**
	 * 上传时间
	 */
	private String time;
	/**
	 * 评论列表
	 */
	private List<PageComment> commentList;
	public void setId(long id) {
		this.id = id;
	}
	public long getId() {
		return this.id;
	}
	public void setPhotoId(long photoId) {
		this.photoId = photoId;
	}
	public long getPhotoId() {
		return this.photoId;
	}
	public void setShareCount(long shareCount) {
		this.shareCount = shareCount;
	}
	public long getShareCount() {
		return this.shareCount;
	}
	public void setUserIdList(List<Long> userIdList) {
		this.userIdList = userIdList;
	}
	public List<Long> getUserIdList() {
		return this.userIdList;
	}
	public void setVoteCount(long voteCount) {
		this.voteCount = voteCount;
	}
	public long getVoteCount() {
		return this.voteCount;
	}
	public void setCommentCount(long commentCount) {
		this.commentCount = commentCount;
	}
	public long getCommentCount() {
		return this.commentCount;
	}
	public void setTime(String time) {
		this.time = time;
	}
	public String getTime() {
		return this.time;
	}
	public void setCommentList(List<PageComment> commentList) {
		this.commentList = commentList;
	}
	public List<PageComment> getCommentList() {
		return this.commentList;
	}
}
