/**
 * Autogenerated by renren-api2-generator 2013-11-21 17:47:04
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;

import java.io.File;
import java.util.*;

import com.renren.api.AccessToken;
import com.renren.api.ObjectMappingException;
import com.renren.api.RennException;
import com.renren.api.RennExecutor;
import com.renren.api.RennParam;
import com.renren.api.RennRequest;
import com.renren.api.RennRequest.Method;
import com.renren.api.RennResponse;
import com.renren.api.mapper.JsonMappingException;
import com.renren.api.mapper.ObjectMapper;

public class PublicService {
	private RennExecutor executor;

    private AccessToken token;

    private ObjectMapper mapper;
	
    /**
     * @param executor
     * @param token
     * @param mapper
     */
    public PublicService(RennExecutor executor, AccessToken token, ObjectMapper mapper) {
        super();
        this.executor = executor;
        this.token = token;
        this.mapper = mapper;
    }

    /**
     * 发送文本
     * @param content 内容
     * @param userId 目标用户id
     * @return Integer 发送成功返回1
     * @throws   RennException 
     * SERVICE_UNAVALIALABLE 服务端临时不可用 
     */
    public Integer sendPublicPlatformText (String  content, Long  userId) throws RennException {
        Map<String, String> textParams = new HashMap<String, String>();
        if (content != null) {
	    textParams.put("content", content);
        }
        if (userId != null) {
            textParams.put("userId", RennParam.asString(userId));
        }
        Map<String, String> bodyParams = new HashMap<String, String>();
        Map<String, File[]> fileParams = new HashMap<String, File[]>();
        RennRequest request = new RennRequest("/v2/public/platform/text/send", Method.POST, textParams, bodyParams, fileParams, token);
        RennResponse response = executor.execute(request);
        try {
            return (Integer)mapper.mapCommon(response.getResponse().toString(), Integer.class);
        } catch (JsonMappingException e) {
            throw new ObjectMappingException();
        }
    }
    /**
     * 回复图片
     * @param originalSource 大图
     * @param userId 目标用户id
     * @param headSource 小图
     * @return Integer 发送成功返回1
     * @throws   RennException 
     * SERVICE_UNAVALIALABLE 服务端临时不可用 
     */
    public Integer sendPublicPlatformImage (String  originalSource, Long  userId, String  headSource) throws RennException {
        Map<String, String> textParams = new HashMap<String, String>();
        if (originalSource != null) {
	    textParams.put("originalSource", originalSource);
        }
        if (userId != null) {
            textParams.put("userId", RennParam.asString(userId));
        }
        if (headSource != null) {
	    textParams.put("headSource", headSource);
        }
        Map<String, String> bodyParams = new HashMap<String, String>();
        Map<String, File[]> fileParams = new HashMap<String, File[]>();
        RennRequest request = new RennRequest("/v2/public/platform/image/send", Method.POST, textParams, bodyParams, fileParams, token);
        RennResponse response = executor.execute(request);
        try {
            return (Integer)mapper.mapCommon(response.getResponse().toString(), Integer.class);
        } catch (JsonMappingException e) {
            throw new ObjectMappingException();
        }
    }
}
