/**
 * Autogenerated by renren-api2-generator 2013-11-21 17:47:03
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
import java.util.*;
/**
 *
 * 评价回复
 */
public class ReplyEvaluation {
	
	/**
	 * ugc id
	 */
	private long resourceId;
	/**
	 * 回复者id
	 */
	private int ownerId;
	/**
	 * 回复者名字
	 */
	private String ownerName;
	/**
	 * 被回复者id
	 */
	private int replyerId;
	/**
	 * 回复的内容
	 */
	private String replyContent;
	/**
	 * 被回复者名字
	 */
	private String replyerName;
	/**
	 * 被回复者头像url
	 */
	private String replyerTinyurl;
	/**
	 * 回复的时间
	 */
	private String replyTime;
	public void setResourceId(long resourceId) {
		this.resourceId = resourceId;
	}
	public long getResourceId() {
		return this.resourceId;
	}
	public void setOwnerId(int ownerId) {
		this.ownerId = ownerId;
	}
	public int getOwnerId() {
		return this.ownerId;
	}
	public void setOwnerName(String ownerName) {
		this.ownerName = ownerName;
	}
	public String getOwnerName() {
		return this.ownerName;
	}
	public void setReplyerId(int replyerId) {
		this.replyerId = replyerId;
	}
	public int getReplyerId() {
		return this.replyerId;
	}
	public void setReplyContent(String replyContent) {
		this.replyContent = replyContent;
	}
	public String getReplyContent() {
		return this.replyContent;
	}
	public void setReplyerName(String replyerName) {
		this.replyerName = replyerName;
	}
	public String getReplyerName() {
		return this.replyerName;
	}
	public void setReplyerTinyurl(String replyerTinyurl) {
		this.replyerTinyurl = replyerTinyurl;
	}
	public String getReplyerTinyurl() {
		return this.replyerTinyurl;
	}
	public void setReplyTime(String replyTime) {
		this.replyTime = replyTime;
	}
	public String getReplyTime() {
		return this.replyTime;
	}
}
