/**
 * Autogenerated by renren-api2-generator 2014-04-16 15:13:50
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
import java.util.*;
/**
 *
 * 公钥信息
 */
public class RsaKey {
	
	/**
	 * 公钥
	 */
	private String publicKey;
	/**
	 * 过期时间
	 */
	private long expirationTime;
	public void setPublicKey(String publicKey) {
		this.publicKey = publicKey;
	}
	public String getPublicKey() {
		return this.publicKey;
	}
	public void setExpirationTime(long expirationTime) {
		this.expirationTime = expirationTime;
	}
	public long getExpirationTime() {
		return this.expirationTime;
	}
}
