/**
 * Autogenerated by renren-api2-generator 2013-03-23 13:10:03
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
/**
 * 性别的种类
 */
 public enum Sex {
	/*
	 * 女性
	 */
	FEMALE,	
	/*
	 * 男性
	 */
	MALE;	
}
