/**
 * Autogenerated by renren-api2-generator 2013-03-13 15:27:21
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;

import java.io.File;
import java.util.*;

import com.renren.api.AccessToken;
import com.renren.api.ObjectMappingException;
import com.renren.api.RennException;
import com.renren.api.RennExecutor;
import com.renren.api.RennParam;
import com.renren.api.RennRequest;
import com.renren.api.RennRequest.Method;
import com.renren.api.RennResponse;
import com.renren.api.mapper.JsonMappingException;
import com.renren.api.mapper.ObjectMapper;

public class ShareService {
	private RennExecutor executor;

    private AccessToken token;

    private ObjectMapper mapper;
	
    /**
     * @param executor
     * @param token
     * @param mapper
     */
    public ShareService(RennExecutor executor, AccessToken token, ObjectMapper mapper) {
        super();
        this.executor = executor;
        this.token = token;
        this.mapper = mapper;
    }

    /**
     * 获取某个用户的某个分享
     * @param shareId 分享ID
     * @param ownerId 分享所有者ID
     * @return Share 分享
     * @throws   RennException 
     * OWNER_NOT_EXIST 分享所有者不存在。 
     * SHARE_NOT_EXIST 分享不存在。 
     */
    public Share getShare (Long  shareId, Long  ownerId) throws RennException {
        Map<String, String> textParams = new HashMap<String, String>();
        textParams.put("shareId", RennParam.asString(shareId));
        textParams.put("ownerId", RennParam.asString(ownerId));
        Map<String, String> bodyParams = new HashMap<String, String>();
        Map<String, File> fileParams = new HashMap<String, File>();
        RennRequest request = new RennRequest("/v2/share/get", Method.GET, textParams, bodyParams, fileParams, token);
        RennResponse response = executor.execute(request);
        try {
            return (Share)mapper.mapCommon(response.getResponse().toString(), Share.class);
        } catch (JsonMappingException e) {
            throw new ObjectMappingException();
        }
    }
    /**
     * 以分页的方式获取某个用户的分享列表
     * @param ownerId 分享所有者ID
     * @param pageSize 页面大小。取值范围1-100，默认大小20
     * @param pageNumber 页码。取值大于零，默认值为1
     * @return Share 分享
     * @throws   RennException 
     * OWNER_NOT_EXIST 分享所有者不存在。 
     * PAGE_SIZE_NOT_IN_RANGE 页面大小不在1-100范围内。 
     * PAGE_NUMBER_MUST_LARGER_0 页码必须大于0。 
     */
    public Share [] listShare (Long  ownerId, Integer  pageSize, Integer  pageNumber) throws RennException {
        Map<String, String> textParams = new HashMap<String, String>();
        textParams.put("ownerId", RennParam.asString(ownerId));
        if (pageSize != null) {
            textParams.put("pageSize", RennParam.asString(pageSize));
        }
        if (pageNumber != null) {
            textParams.put("pageNumber", RennParam.asString(pageNumber));
        }
        Map<String, String> bodyParams = new HashMap<String, String>();
        Map<String, File> fileParams = new HashMap<String, File>();
        RennRequest request = new RennRequest("/v2/share/list", Method.GET, textParams, bodyParams, fileParams, token);
        RennResponse response = executor.execute(request);
        try {
            return (Share [])mapper.mapCommon(response.getResponse().toString(), Share.class);
        } catch (JsonMappingException e) {
            throw new ObjectMappingException();
        }
    }
}
