/**
 * Autogenerated by renren-api2-generator 2014-04-16 15:13:50
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
/**
 * 
 */
 public enum ShareType {
	/*
	 * 视频类型分享
	 */
	TYPE_VIDEO,	
	/*
	 * 日志类型分享
	 */
	TYPE_BLOG,	
	/*
	 * 照片类型分享
	 */
	TYPE_PHOTO,	
	/*
	 * 相册类型分享
	 */
	TYPE_ALBUM;	
}
