/**
 * Autogenerated by renren-api2-generator 2013-06-06 15:02:04
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
import java.util.*;
/**
 *
 * 分享
 */
public class Share {
	
	/**
	 * 分享的ID
	 */
	private long id;
	/**
	 * 被分享的url
	 */
	private String url;
	/**
	 * 分享所有者的ID
	 */
	private long userId;
	/**
	 * 最初发起此分享的用户ID
	 */
	private long sourceUserId;
	/**
	 * 分享的缩略图
	 */
	private String thumbUrl;
	/**
	 * 分享的标题
	 */
	private String title;
	/**
	 * 分享内容的摘要
	 */
	private String summary;
	/**
	 * 分享被评论的次数
	 */
	private String commentCount;
	/**
	 * 分享产生的时间
	 */
	private String shareTime;
	/**
	 * 被分享资源的ID
	 */
	private long resourceId;
	/**
	 * 被分享资源所有者的用户ID
	 */
	private long resourceUserId;
	public void setId(long id) {
		this.id = id;
	}
	public long getId() {
		return this.id;
	}
	public void setUrl(String url) {
		this.url = url;
	}
	public String getUrl() {
		return this.url;
	}
	public void setUserId(long userId) {
		this.userId = userId;
	}
	public long getUserId() {
		return this.userId;
	}
	public void setSourceUserId(long sourceUserId) {
		this.sourceUserId = sourceUserId;
	}
	public long getSourceUserId() {
		return this.sourceUserId;
	}
	public void setThumbUrl(String thumbUrl) {
		this.thumbUrl = thumbUrl;
	}
	public String getThumbUrl() {
		return this.thumbUrl;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getTitle() {
		return this.title;
	}
	public void setSummary(String summary) {
		this.summary = summary;
	}
	public String getSummary() {
		return this.summary;
	}
	public void setCommentCount(String commentCount) {
		this.commentCount = commentCount;
	}
	public String getCommentCount() {
		return this.commentCount;
	}
	public void setShareTime(String shareTime) {
		this.shareTime = shareTime;
	}
	public String getShareTime() {
		return this.shareTime;
	}
	public void setResourceId(long resourceId) {
		this.resourceId = resourceId;
	}
	public long getResourceId() {
		return this.resourceId;
	}
	public void setResourceUserId(long resourceUserId) {
		this.resourceUserId = resourceUserId;
	}
	public long getResourceUserId() {
		return this.resourceUserId;
	}
}
