/**
 * Autogenerated by renren-api2-generator 2013-06-06 15:02:04
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
import java.util.*;
/**
 *
 * 状态
 */
public class Status {
	
	/**
	 * 状态的ID
	 */
	private long id;
	/**
	 * 状态所有者的用户ID
	 */
	private long ownerId;
	/**
	 * 状态的内容，未处理过ubb的状态原文本
	 */
	private String content;
	/**
	 * 状态发布的时间
	 */
	private String createTime;
	/**
	 * 状态被转发的次数
	 */
	private int shareCount;
	/**
	 * 状态被回复的次数
	 */
	private int commentCount;
	/**
	 * 被分享状态的状态ID（分享的状态才会有）
	 */
	private long sharedStatusId;
	/**
	 * 被分享的根状态的用户ID（分享的状态才会有）
	 */
	private long sharedUserId;
	public void setId(long id) {
		this.id = id;
	}
	public long getId() {
		return this.id;
	}
	public void setOwnerId(long ownerId) {
		this.ownerId = ownerId;
	}
	public long getOwnerId() {
		return this.ownerId;
	}
	public void setContent(String content) {
		this.content = content;
	}
	public String getContent() {
		return this.content;
	}
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}
	public String getCreateTime() {
		return this.createTime;
	}
	public void setShareCount(int shareCount) {
		this.shareCount = shareCount;
	}
	public int getShareCount() {
		return this.shareCount;
	}
	public void setCommentCount(int commentCount) {
		this.commentCount = commentCount;
	}
	public int getCommentCount() {
		return this.commentCount;
	}
	public void setSharedStatusId(long sharedStatusId) {
		this.sharedStatusId = sharedStatusId;
	}
	public long getSharedStatusId() {
		return this.sharedStatusId;
	}
	public void setSharedUserId(long sharedUserId) {
		this.sharedUserId = sharedUserId;
	}
	public long getSharedUserId() {
		return this.sharedUserId;
	}
}
