/**
 * Autogenerated by renren-api2-generator 2013-11-21 17:47:03
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
/**
 * ticket 类型
 */
 public enum TicketType {
	/*
	 * WAP上的ticket
	 */
	WAP,	
	/*
	 * web上的ticket
	 */
	WEB;	
}
