/**
 * Autogenerated by renren-api2-generator 2013-11-21 17:47:03
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;

import java.io.File;
import java.util.*;

import com.renren.api.AccessToken;
import com.renren.api.ObjectMappingException;
import com.renren.api.RennException;
import com.renren.api.RennExecutor;
import com.renren.api.RennParam;
import com.renren.api.RennRequest;
import com.renren.api.RennRequest.Method;
import com.renren.api.RennResponse;
import com.renren.api.mapper.JsonMappingException;
import com.renren.api.mapper.ObjectMapper;

public class TokenService {
	private RennExecutor executor;

    private AccessToken token;

    private ObjectMapper mapper;
	
    /**
     * @param executor
     * @param token
     * @param mapper
     */
    public TokenService(RennExecutor executor, AccessToken token, ObjectMapper mapper) {
        super();
        this.executor = executor;
        this.token = token;
        this.mapper = mapper;
    }

    /**
     * 根据ticket或sid换access token
     * @param ticket ticket 或 sid
     * @param type ticket的类型
     * @return String token内容
     * @throws   RennException 
     * INVALID_TICKET ticket无效。 
     * SERVICE_BUSY 服务器繁忙，请稍后再试。 
     * NO_PERMISSION 没有权限调用。 
     */
    public String getToken (String  ticket, TicketType  type) throws RennException {
        Map<String, String> textParams = new HashMap<String, String>();
        if (ticket != null) {
	    textParams.put("ticket", ticket);
        }
        if (type != null) {
            textParams.put("type", RennParam.asString(type));
        }
        Map<String, String> bodyParams = new HashMap<String, String>();
        Map<String, File[]> fileParams = new HashMap<String, File[]>();
        RennRequest request = new RennRequest("/v2/token/get", Method.GET, textParams, bodyParams, fileParams, token);
        RennResponse response = executor.execute(request);
        try {
            return (String)mapper.mapCommon(response.getResponse().toString(), String.class);
        } catch (JsonMappingException e) {
            throw new ObjectMappingException();
        }
    }
}
