/**
 * Autogenerated by renren-api2-generator 2014-04-23 18:03:22
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
import java.util.*;
/**
 *
 * UBB表情
 */
public class Ubb {
	
	/**
	 * UBB内容,例如：(大笑)
	 */
	private String ubb;
	/**
	 * UBB替换后图片的url
	 */
	private String url;
	/**
	 * UBB的描述
	 */
	private String description;
	public void setUbb(String ubb) {
		this.ubb = ubb;
	}
	public String getUbb() {
		return this.ubb;
	}
	public void setUrl(String url) {
		this.url = url;
	}
	public String getUrl() {
		return this.url;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public String getDescription() {
		return this.description;
	}
}
