/**
 * Autogenerated by renren-api2-generator 2014-04-23 18:03:22
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;

import java.io.File;
import java.util.*;

import com.renren.api.AccessToken;
import com.renren.api.ObjectMappingException;
import com.renren.api.RennException;
import com.renren.api.RennExecutor;
import com.renren.api.RennParam;
import com.renren.api.RennRequest;
import com.renren.api.RennRequest.Method;
import com.renren.api.RennResponse;
import com.renren.api.mapper.JsonMappingException;
import com.renren.api.mapper.ObjectMapper;

public class UserService {
	private RennExecutor executor;

    private AccessToken token;

    private ObjectMapper mapper;
	
    /**
     * @param executor
     * @param token
     * @param mapper
     */
    public UserService(RennExecutor executor, AccessToken token, ObjectMapper mapper) {
        super();
        this.executor = executor;
        this.token = token;
        this.mapper = mapper;
    }

    /**
     * 批量获取用户信息
     * @param userIds 批量获取的用户IDs,最多支持50个
     * @return User 用户
     * @throws   RennException 
     * SERVICE_UNAVAILABLE 服务端临时不可用 
     * INVALID_USERID userId参数不合法 
     * MISSING_USERID 缺少userId参数 
     * HAVE_PRIVACY 由于隐私设置，没有权限查看 
     */
    public User [] batchUser (Long [] userIds) throws RennException {
        Map<String, String> textParams = new HashMap<String, String>();
        if (userIds != null) {
            textParams.put("userIds", RennParam.asString(userIds));
        }
        Map<String, String> bodyParams = new HashMap<String, String>();
        Map<String, File[]> fileParams = new HashMap<String, File[]>();
        RennRequest request = new RennRequest("/v2/user/batch", Method.GET, textParams, bodyParams, fileParams, token);
        RennResponse response = executor.execute(request);
        try {
            return (User [])mapper.mapCommon(response.getResponse().toString(), User.class);
        } catch (JsonMappingException e) {
            throw new ObjectMappingException();
        }
    }
    /**
     * 获取用户信息
     * @param userId 用户ID，不传时表示获取access_token对应的用户信息
     * @return User 用户
     * @throws   RennException 
     * SERVICE_UNAVAILABLE 服务端临时不可用 
     * INVALID_USERID userId参数不合法 
     * USER_NOT_EXIST 用户不存在 
     * MISSING_USERID 缺少userId参数 
     * HAVE_PRIVACY 由于隐私设置，没有权限查看 
     */
    public User getUser (Long  userId) throws RennException {
        Map<String, String> textParams = new HashMap<String, String>();
        if (userId != null) {
            textParams.put("userId", RennParam.asString(userId));
        }
        Map<String, String> bodyParams = new HashMap<String, String>();
        Map<String, File[]> fileParams = new HashMap<String, File[]>();
        RennRequest request = new RennRequest("/v2/user/get", Method.GET, textParams, bodyParams, fileParams, token);
        RennResponse response = executor.execute(request);
        try {
            return (User)mapper.mapCommon(response.getResponse().toString(), User.class);
        } catch (JsonMappingException e) {
            throw new ObjectMappingException();
        }
    }
    /**
     * 获取当前登录用户未安装某应用里的好友列表
     * @return User 用户
     * @throws   RennException 
     * SERVICE_UNAVAILABLE 服务端临时不可用 
     */
    public User [] listUserFriendUninstall () throws RennException {
        Map<String, String> textParams = new HashMap<String, String>();
        Map<String, String> bodyParams = new HashMap<String, String>();
        Map<String, File[]> fileParams = new HashMap<String, File[]>();
        RennRequest request = new RennRequest("/v2/user/friend/uninstall/list", Method.GET, textParams, bodyParams, fileParams, token);
        RennResponse response = executor.execute(request);
        try {
            return (User [])mapper.mapCommon(response.getResponse().toString(), User.class);
        } catch (JsonMappingException e) {
            throw new ObjectMappingException();
        }
    }
    /**
     * 获取当前登录用户在某个应用里的好友列表
     * @return User 用户
     * @throws   RennException 
     * SERVICE_UNAVAILABLE 服务端临时不可用 
     */
    public User [] listUserFriendApp () throws RennException {
        Map<String, String> textParams = new HashMap<String, String>();
        Map<String, String> bodyParams = new HashMap<String, String>();
        Map<String, File[]> fileParams = new HashMap<String, File[]>();
        RennRequest request = new RennRequest("/v2/user/friend/app/list", Method.GET, textParams, bodyParams, fileParams, token);
        RennResponse response = executor.execute(request);
        try {
            return (User [])mapper.mapCommon(response.getResponse().toString(), User.class);
        } catch (JsonMappingException e) {
            throw new ObjectMappingException();
        }
    }
    /**
     * 获取某个用户的好友列表
     * @param userId 用户ID
     * @param pageSize 页面大小。取值范围1-100，默认大小20
     * @param pageNumber 页码。取值大于零，默认值为1
     * @return User 用户
     * @throws   RennException 
     * SERVICE_UNAVAILABLE 服务端临时不可用 
     * PAGESIZE_NOT_IN_RANGE 页面大小不在1-100范围内。 
     * PAGE_NUMBER_MUST_LARGER_0 页码必须大于0。 
     */
    public User [] listUserFriend (Long  userId, Integer  pageSize, Integer  pageNumber) throws RennException {
        Map<String, String> textParams = new HashMap<String, String>();
        if (userId != null) {
            textParams.put("userId", RennParam.asString(userId));
        }
        if (pageSize != null) {
            textParams.put("pageSize", RennParam.asString(pageSize));
        }
        if (pageNumber != null) {
            textParams.put("pageNumber", RennParam.asString(pageNumber));
        }
        Map<String, String> bodyParams = new HashMap<String, String>();
        Map<String, File[]> fileParams = new HashMap<String, File[]>();
        RennRequest request = new RennRequest("/v2/user/friend/list", Method.GET, textParams, bodyParams, fileParams, token);
        RennResponse response = executor.execute(request);
        try {
            return (User [])mapper.mapCommon(response.getResponse().toString(), User.class);
        } catch (JsonMappingException e) {
            throw new ObjectMappingException();
        }
    }
    /**
     * 以分页的方式获取某个用户与当前登录用户的共同好友
     * @param userId 用户ID
     * @return User 用户
     * @throws   RennException 
     * SERVICE_UNAVAILABLE 服务端临时不可用 
     */
    public User [] listUserFriendMutual (Long  userId) throws RennException {
        Map<String, String> textParams = new HashMap<String, String>();
        if (userId != null) {
            textParams.put("userId", RennParam.asString(userId));
        }
        Map<String, String> bodyParams = new HashMap<String, String>();
        Map<String, File[]> fileParams = new HashMap<String, File[]>();
        RennRequest request = new RennRequest("/v2/user/friend/mutual/list", Method.GET, textParams, bodyParams, fileParams, token);
        RennResponse response = executor.execute(request);
        try {
            return (User [])mapper.mapCommon(response.getResponse().toString(), User.class);
        } catch (JsonMappingException e) {
            throw new ObjectMappingException();
        }
    }
    /**
     * 获取当前登录用户信息
     * @return User 用户
     * @throws   RennException 
     * SERVICE_UNAVAILABLE 服务端临时不可用 
     * USER_NOT_EXIST 用户不存在 
     */
    public User getUserLogin () throws RennException {
        Map<String, String> textParams = new HashMap<String, String>();
        Map<String, String> bodyParams = new HashMap<String, String>();
        Map<String, File[]> fileParams = new HashMap<String, File[]>();
        RennRequest request = new RennRequest("/v2/user/login/get", Method.GET, textParams, bodyParams, fileParams, token);
        RennResponse response = executor.execute(request);
        try {
            return (User)mapper.mapCommon(response.getResponse().toString(), User.class);
        } catch (JsonMappingException e) {
            throw new ObjectMappingException();
        }
    }
}
