/**
 * Autogenerated by renren-api2-generator 2014-04-16 15:13:50
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
import java.util.*;
/**
 *
 * 用户
 */
public class User {
	
	/**
	 * 用户ID
	 */
	private long id;
	/**
	 * 用户名
	 */
	private String name;
	/**
	 * 用户头像列表
	 */
	private List<Image> avatar;
	/**
	 * 是否为星级用户，值“1”表示“是”；值“0”表示“不是”
	 */
	private int star;
	/**
	 * 用户基本信息
	 */
	private BasicInformation basicInformation;
	/**
	 * 用户学校信息
	 */
	private List<School> education;
	/**
	 * 工作信息
	 */
	private List<Work> work;
	/**
	 * 喜欢
	 */
	private List<Like> like;
	/**
	 * 感情状态
	 */
	private EmotionalState emotionalState;
	public void setId(long id) {
		this.id = id;
	}
	public long getId() {
		return this.id;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getName() {
		return this.name;
	}
	public void setAvatar(List<Image> avatar) {
		this.avatar = avatar;
	}
	public List<Image> getAvatar() {
		return this.avatar;
	}
	public void setStar(int star) {
		this.star = star;
	}
	public int getStar() {
		return this.star;
	}
	public void setBasicInformation(BasicInformation basicInformation) {
		this.basicInformation = basicInformation;
	}
	public BasicInformation getBasicInformation() {
		return this.basicInformation;
	}
	public void setEducation(List<School> education) {
		this.education = education;
	}
	public List<School> getEducation() {
		return this.education;
	}
	public void setWork(List<Work> work) {
		this.work = work;
	}
	public List<Work> getWork() {
		return this.work;
	}
	public void setLike(List<Like> like) {
		this.like = like;
	}
	public List<Like> getLike() {
		return this.like;
	}
	public void setEmotionalState(EmotionalState emotionalState) {
		this.emotionalState = emotionalState;
	}
	public EmotionalState getEmotionalState() {
		return this.emotionalState;
	}
}
