/**
 * Autogenerated by renren-api2-generator 2013-11-21 17:47:03
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.renren.api.service;
import java.util.*;
/**
 *
 * VIP信息
 */
public class VIPInfo {
	
	/**
	 * 用户ID
	 */
	private long id;
	/**
	 * 是否是VIP
	 */
	private boolean isVip;
	/**
	 * VIP等级
	 */
	private int vipLevel;
	public void setId(long id) {
		this.id = id;
	}
	public long getId() {
		return this.id;
	}
	public void setIsVip(boolean isVip) {
		this.isVip = isVip;
	}
	public boolean getIsVip() {
		return this.isVip;
	}
	public void setVipLevel(int vipLevel) {
		this.vipLevel = vipLevel;
	}
	public int getVipLevel() {
		return this.vipLevel;
	}
}
